name: Javascript CI
on: ["push"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use node 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0
    - name: cd
      run: cd ./forestfrontend
    - name: Install dependencies
      run: npm ci    
      working-directory: .
    - name: install vitejs plugin-vue
      run: npm install --save-dev @vitejs/plugin-vue
    - name: Run tests
      run: npm run test:unit
      working-directory: .
