name: Javascript CI
on: ["push"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use node 16.13.1
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.1
    
    - name: Install dependencies
      run: npm ci 
    - name: run tests
      run: npm run test:unit
