name: Javascript CI
on: ["push"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use node 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0
    - name: cd
      run: cd ./forestfrontend
    - name: install project dependecies
      run: npm install
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test:unit
